#!/bin/sh
export XDG_CURRENT_DESKTOP=sway
export XDG_DESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
#export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GTK_THEME=Catppuccin-Macchiato-Standard-Peach-dark
export ICON_THEME=Tela-circle-purple-dark

dbus-run-session sway
