#!/bin/sh
# XDG_RUNTIME_DIR is set by elogind
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

export XDG_CURRENT_DESKTOP=sway
export XDG_DESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

# Firefox and Thunderbird wayland support
export MOZ_ENABLE_WAYLAND=1

# Theming
#export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GTK_THEME=Catppuccin-Macchiato-Standard-Peach-Dark
export ICON_THEME=Tela-circle-purple-dark
export XCURSOR_THEME=Catppuccin-Macchiato-Peach-Cursors

# One of these should work
#dbus-run-session sway
sway
