format = ' $username$directory$character'
right_format = '$git_branch$git_status'
continuation_prompt = '::: '
add_newline = false

[character]
success_symbol = '[%](bold blue)'
error_symbol   = '[%](bold red)'
vimcmd_symbol  = '[:](bold blue)'
vimcmd_replace_one_symbol = '[:](yellow)'
vimcmd_replace_symbol     = '[:](yellow)'
vimcmd_visual_symbol      = '[:](yellow)'

[directory]
style = 'green'
truncation_symbol = '::'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'yellow'

[git_status]
format = '[$all_status]($style)'
style = 'yellow'
modified = '[*](red)'
staged = '[+](green)'
untracked = '[?](purple)'
ahead = ''
behind = ''
conflicted = ''
deleted = ''
diverged = ''
renamed = ''
stashed = ''

[username]
format = '[@$user]($style) '
style_user = 'bold red'
show_always = true
